### imagemapa Latitude, Longitude and Zoom

GET https://imagemapa.com.br/?lat=-23.6153206&lng=-46.7669051&z=11 HTTP/1.1

### imagemapa PNG, JPG ou WEBP

GET https://imagemapa.com.br/?lat=-23.6153206&lng=-46.7669051&z=11&format=png HTTP/1.1

### imagemapa quality 0 - 1

GET https://imagemapa.com.br/?lat=-23.6153206&lng=-46.7669051&z=11&format=jpg&quality=0.5 HTTP/1.1

### imagemapa size 100 - 1000

GET https://imagemapa.com.br/?lat=-23.6153206&lng=-46.7669051&z=11&format=jpg&quality=0.5&width=500&height=500 HTTP/1.1